### ISSUE TITLE
Correct wrong code syntax

### ISSUE THREAD

**Issue by corrado877** [corrado877/Testing-Enviroment-Coop.#2]
Wrong code in line 13

**Comment by corrado877** [comment]
@Corrado892 in the " the story of my life" file change code syntax in line 13. Change `<h3>` with `<h4>`

**Comment by Corrado892** [comment]
> @Corrado877 changed syntax as requested https://github.com/corrado877/Testing-Enviroment-Coop./blob/640204cf6da01a3f54fbdb52a27bdff3ab7b5020/The%20story%20of%20my%20life#L18
